version: '2'
services:
  web:
    image: node
    ports:
    - "8082:8080"
    working_dir: /server
    volumes:
    - ./lib:/server
    - ./node_modules:/server/node_modules
    command: "/server/node_modules/.bin/nodemon /server/index.js"
